### ISSUE TITLE
No encuentro los archivos de Formato

### ISSUE THREAD

**Issue by diguardia** [pmoracho/parseit#6]
Hola!
Cómo estás? 
Di por casualidad con este proyecto. Estaba pensando hace rato hacer algo igual. En realidad quería hacer algún tool bidireccional (para separar en el código de mi app la lógica de conseguir los datos de como presentarlo). 
Te hago una consulta: No encuentro los archivos de formato de ejemplo. Están subidos al repo?
Un abrazo

**Comment by pmoracho** [comment]
[Este](https://github.com/pmoracho/parseit/blob/master/parseit.fmt) es el archivo json con la definición de los formatos.
Saludos
